name: Deployment Matrix Action
description: Outputs a matrix that deploys code to the correct environment.
inputs:
  envs:
    description: Environment mapping
    required: false
    default: |
      prod: master
      dev: dev
      stage: stage
      test: test
  jobs:
    description: List/CSV of jobs to deploy per environment.
    required: false
    default: app
outputs:
  matrix:
    description: Matrix JSON to be used in another job.
  count:
    description: Count of matching environments.
runs:
  using: 'node22'
  main: 'dist/index.js'
