name: Tests

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install Dependencies
        run: npm ci --install-dev
      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install Dependencies
        run: npm ci --install-dev
      - name: Lint
        run: npm run test

  test-gen-deploy-matrix:
    name: Test Generate Deployment Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Matrix
        uses: ./
        id: gen-matrix
        with:
          envs: |
            prod: main
            dev: dev
            stage: stage
            test: test
            release:
              tag: "*"

  test-output:
    name: Test Output
    runs-on: ubuntu-latest
    needs: [test-gen-deploy-matrix]
    strategy:
      matrix: ${{ fromJson(needs.test-gen-deploy-matrix.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.name }}

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref_name, '.')
    needs: [build, lint, test, test-gen-deploy-matrix, test-output]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Changelog
        id: changelog
        uses: gabe565/changelog-generator@v1
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog }}
      - uses: nowactions/update-majorver@v1
